const KEY="slot-arena-live-v1";
const fresh=()=>({round:1,duration:600,remaining:600,phase:"idle",countdown:30,slot:"Da selezionare",chooser:"—",bet:.5,players:Array.from({length:10},(_,i)=>({id:i+1,name:`Giocatore ${i+1}`,credit:100,active:true,station:i+1}))});
let state=load(),timerId,toastId;const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(Number(n)||0);
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)),phase:"idle"}}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify({...state,phase:"idle"}))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function sorted(){return [...state.players].sort((a,b)=>Number(b.active)-Number(a.active)||b.credit-a.credit||a.id-b.id)}
function time(s){s=Math.max(0,Math.ceil(s));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function render(){
  $("roundNumber").textContent=state.round;$("roundInput").value=state.round;$("minutesInput").value=Math.round(state.duration/60);$("countdownInput").value=state.countdown;
  $("slotName").textContent=state.slot;$("slotChooser").textContent=state.chooser;$("slotInput").value=state.slot==="Da selezionare"?"":state.slot;$("chooserInput").value=state.chooser==="—"?"":state.chooser;$("betInput").value=state.bet;$("betValue").textContent=euro(state.bet);
  $("timer").textContent=time(state.remaining);$("timer").classList.toggle("warning",state.remaining<=60&&state.remaining>30);$("timer").classList.toggle("danger",state.remaining<=30);
  const labels={idle:"IN ATTESA",running:"ROUND IN CORSO",paused:"IN PAUSA",countdown:"COUNTDOWN"};$("phasePill").textContent=labels[state.phase];$("eventStatus").textContent=state.phase==="running"?"LIVE":labels[state.phase];$("timerLabel").textContent=state.phase==="running"?"TEMPO RESIDUO":state.phase==="paused"?"ROUND IN PAUSA":"PRONTI PER INIZIARE";$("progressFill").style.width=`${Math.max(0,state.remaining/state.duration*100)}%`;
  const active=state.players.filter(p=>p.active).length;$("activeCount").textContent=active;$("eliminatedCount").textContent=10-active;
  $("leaderboard").innerHTML=sorted().map((p,i)=>`<div class="player-row ${p.active&&i<3?`top-${i+1}`:""} ${p.active?"":"eliminated"}"><span class="rank">${p.active?String(i+1).padStart(2,"0"):"—"}</span><div class="player-main"><span class="avatar">${esc(p.name.slice(0,2).toUpperCase())}</span><div><div class="player-name">${esc(p.name)}</div><div class="player-status">${p.active?"IN GARA":"ELIMINATO"}</div></div></div><span class="station">P${p.station}</span><strong class="credit">${euro(p.credit)}</strong></div>`).join("");
  $("adminPlayers").innerHTML=sorted().map(p=>`<div class="admin-player ${p.active?"":"is-out"}" data-id="${p.id}"><span class="position">P${p.station}</span><input class="name-input" value="${esc(p.name)}"><input class="credit-input" type="number" min="0" step=".01" value="${Number(p.credit).toFixed(2)}"><button class="state-btn">${p.active?"●":"×"}</button></div>`).join("");
  document.querySelectorAll(".admin-player").forEach(row=>{const p=state.players.find(x=>x.id===+row.dataset.id);const name=row.querySelector(".name-input"),credit=row.querySelector(".credit-input");name.oninput=e=>{p.name=e.target.value||`Giocatore ${p.id}`;save()};name.onblur=render;credit.oninput=e=>{p.credit=Math.max(0,+e.target.value||0);save()};credit.onblur=render;row.querySelector(".state-btn").onclick=()=>{p.active=!p.active;render();checkFinal()}});
  save();
}
function start(){if(state.phase==="running")return;state.phase="running";clearInterval(timerId);timerId=setInterval(()=>{state.remaining--;if(state.remaining<=0){state.remaining=0;clearInterval(timerId);state.phase="idle";note("Round terminato")}render()},1000);render()}
function pause(){if(state.phase==="running"){clearInterval(timerId);state.phase="paused";render()}}
function resetTimer(){clearInterval(timerId);state.phase="idle";state.remaining=state.duration;render();note("Cronometro ripristinato")}
function countdown(){clearInterval(timerId);state.phase="countdown";let left=Math.max(3,+$("countdownInput").value||30);state.countdown=left;$("countdownValue").textContent=left;$("countdownSlot").textContent=state.slot.toUpperCase();$("countdownOverlay").classList.add("show");render();timerId=setInterval(()=>{left--;$("countdownValue").textContent=left;if(left<=0){clearInterval(timerId);$("countdownOverlay").classList.remove("show");state.remaining=state.duration;start()}},1000)}
function next(){clearInterval(timerId);state.round++;state.duration=Math.max(60,+$("minutesInput").value*60||600);state.remaining=state.duration;state.phase="idle";render();note(`Round ${state.round} pronto`)}
function eliminate(){const a=state.players.filter(p=>p.active);if(a.length<=3){note("Sono rimasti i tre finalisti");checkFinal();return}const min=Math.min(...a.map(p=>p.credit)),last=a.filter(p=>p.credit===min);if(last.length>1){note("Parità sull’ultimo posto: serve uno spareggio");return}last[0].active=false;render();note(`${last[0].name} eliminato`);checkFinal()}
function checkFinal(){const a=sorted().filter(p=>p.active);if(a.length===3){$("finalists").innerHTML=a.map((p,i)=>`<div class="finalist">${["🥇","🥈","🥉"][i]} ${esc(p.name)}</div>`).join("");$("finalOverlay").classList.add("show")}}
function note(m){clearTimeout(toastId);$("toast").textContent=m;$("toast").classList.add("show");toastId=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function admin(open){$("adminPanel").classList.toggle("open",open);$("scrim").classList.toggle("open",open)}
$("startBtn").onclick=start;$("pauseBtn").onclick=pause;$("resetTimerBtn").onclick=resetTimer;$("countdownBtn").onclick=()=>{admin(false);countdown()};$("nextRoundBtn").onclick=next;$("adminBtn").onclick=()=>admin(true);$("closeAdminBtn").onclick=()=>admin(false);$("scrim").onclick=()=>admin(false);
$("saveSlotBtn").onclick=()=>{state.slot=$("slotInput").value.trim()||"Da selezionare";state.chooser=$("chooserInput").value.trim()||"—";state.bet=Math.max(.1,+$("betInput").value||.5);render();note("Slot aggiornata")};$("eliminateLastBtn").onclick=eliminate;$("sortBtn").onclick=()=>{render();note("Classifica ordinata")};
$("roundInput").onchange=e=>{state.round=Math.max(1,+e.target.value||1);render()};$("minutesInput").onchange=e=>{state.duration=Math.max(60,+e.target.value*60||600);state.remaining=state.duration;render()};
$("fullscreenBtn").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>note("Schermo intero non disponibile"));$("closeFinalBtn").onclick=()=>$("finalOverlay").classList.remove("show");
$("resetAllBtn").onclick=()=>{if(confirm("Ripristinare tutti i dati del torneo?")){clearInterval(timerId);state=fresh();render();note("Torneo ripristinato")}};
document.addEventListener("keydown",e=>{if(e.key==="Escape")admin(false);if((e.ctrlKey||e.metaKey)&&e.key===","){e.preventDefault();admin(true)}});
setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString("it-IT",{hour12:false}),1000);render();
