const KEY="slot-arena-live-v1";
const fresh=()=>({round:1,duration:600,remaining:600,phase:"idle",countdown:30,slot:"Da selezionare",chooser:"—",bet:.5,sound:true,voice:true,players:Array.from({length:10},(_,i)=>({id:i+1,name:`Giocatore ${i+1}`,credit:100,active:true,station:i+1}))});
let state=load(),timerId,toastId,audioContext,currentVoiceClip;const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(Number(n)||0);
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)),phase:"idle"}}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify({...state,phase:"idle"}))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function sorted(){return [...state.players].sort((a,b)=>Number(b.active)-Number(a.active)||b.credit-a.credit||a.id-b.id)}
function time(s){s=Math.max(0,Math.ceil(s));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function audio(){if(!state.sound)return null;audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();return audioContext}
function tone(freq,duration=.12,delay=0,type="sine",volume=.08){const ctx=audio();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.015);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start(start);osc.stop(start+duration+.02)}
function sound(name){if(name==="start"){tone(440,.18,0,"sine",.1);tone(660,.22,.16,"sine",.11);tone(880,.4,.34,"sine",.12)}if(name==="tick")tone(880,.09,0,"square",.055);if(name==="end"){tone(660,.2);tone(440,.3,.18);tone(220,.55,.42,"sine",.12)}if(name==="eliminate"){tone(260,.18,0,"sawtooth",.07);tone(150,.45,.16,"sawtooth",.08)}if(name==="add"){tone(620,.1);tone(820,.18,.1)}}
function italianVoice(){const voices=speechSynthesis.getVoices(),it=voices.filter(v=>v.lang.toLowerCase().startsWith("it"));return it.find(v=>/elsa|alice|federica|isabella|female|donna/i.test(v.name))||it[0]||voices[0]}
function speak(text,interrupt=false){if(!state.voice||!("speechSynthesis" in window))return;if(interrupt)speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(text),voice=italianVoice();if(voice)message.voice=voice;message.lang="it-IT";message.rate=.9;message.pitch=1.08;message.volume=.95;speechSynthesis.speak(message)}
function voiceClip(name){if(!state.voice)return;if(currentVoiceClip){currentVoiceClip.pause();currentVoiceClip.currentTime=0}if("speechSynthesis" in window)speechSynthesis.cancel();currentVoiceClip=$(`voice-${name}`);if(!currentVoiceClip)return;currentVoiceClip.muted=false;currentVoiceClip.volume=.95;currentVoiceClip.currentTime=0;currentVoiceClip.play().catch(()=>note("Premi PROVA LA VOCE per abilitare l’audio"))}
function unlockVoice(){const clip=$("voice-start");if(!clip)return;clip.muted=true;clip.volume=0;clip.play().then(()=>{clip.pause();clip.currentTime=0;clip.muted=false;clip.volume=.95}).catch(()=>{})}
function render(){
  $("roundNumber").textContent=state.round;$("roundInput").value=state.round;$("minutesInput").value=Math.round(state.duration/60);$("countdownInput").value=state.countdown;
  $("slotName").textContent=state.slot;$("slotChooser").textContent=state.chooser;$("slotInput").value=state.slot==="Da selezionare"?"":state.slot;$("chooserInput").value=state.chooser==="—"?"":state.chooser;$("betInput").value=state.bet;$("betValue").textContent=euro(state.bet);
  $("timer").textContent=time(state.remaining);$("timer").classList.toggle("warning",state.remaining<=60&&state.remaining>30);$("timer").classList.toggle("danger",state.remaining<=30);
  const labels={idle:"IN ATTESA",running:"ROUND IN CORSO",paused:"IN PAUSA",countdown:"COUNTDOWN"};$("phasePill").textContent=labels[state.phase];$("eventStatus").textContent=state.phase==="running"?"LIVE":labels[state.phase];$("timerLabel").textContent=state.phase==="running"?"TEMPO RESIDUO":state.phase==="paused"?"ROUND IN PAUSA":"PRONTI PER INIZIARE";$("progressFill").style.width=`${Math.max(0,state.remaining/state.duration*100)}%`;
  const active=state.players.filter(p=>p.active).length;$("activeCount").textContent=active;$("eliminatedCount").textContent=state.players.length-active;$("leaderboard").classList.toggle("compact",state.players.length>10);$("playerLimitLabel").textContent=`${state.players.length} di 16`;$("soundBtn").textContent=state.sound?"🔊":"🔇";$("voiceBtn").textContent=state.voice?"🎙️":"🚫";
  $("leaderboard").innerHTML=sorted().map((p,i)=>`<div class="player-row ${p.active&&i<3?`top-${i+1}`:""} ${p.active?"":"eliminated"}"><span class="rank">${p.active?String(i+1).padStart(2,"0"):"—"}</span><div class="player-main"><span class="avatar">${esc(p.name.slice(0,2).toUpperCase())}</span><div><div class="player-name">${esc(p.name)}</div><div class="player-status">${p.active?"IN GARA":"ELIMINATO"}</div></div></div><span class="station">P${p.station}</span><strong class="credit">${euro(p.credit)}</strong></div>`).join("");
  $("adminPlayers").innerHTML=sorted().map(p=>`<div class="admin-player ${p.active?"":"is-out"}" data-id="${p.id}"><span class="position">P${p.station}</span><input class="name-input" value="${esc(p.name)}"><input class="credit-input" type="number" min="0" step=".01" value="${Number(p.credit).toFixed(2)}"><button class="state-btn">${p.active?"●":"×"}</button></div>`).join("");
  document.querySelectorAll(".admin-player").forEach(row=>{const p=state.players.find(x=>x.id===+row.dataset.id);const name=row.querySelector(".name-input"),credit=row.querySelector(".credit-input");name.oninput=e=>{p.name=e.target.value||`Giocatore ${p.id}`;save()};name.onblur=render;credit.oninput=e=>{p.credit=Math.max(0,+e.target.value||0);save()};credit.onblur=render;row.querySelector(".state-btn").onclick=()=>{p.active=!p.active;render();checkFinal()}});
  save();
}
function start(){if(state.phase==="running")return;sound("start");voiceClip("start");state.phase="running";clearInterval(timerId);timerId=setInterval(()=>{state.remaining--;if(state.remaining===60)voiceClip("minute");if(state.remaining===30)voiceClip("thirty");if(state.remaining===10)voiceClip("ten");if(state.remaining<=0){state.remaining=0;clearInterval(timerId);state.phase="idle";sound("end");voiceClip("end");note("Round terminato")}render()},1000);render()}
function pause(){if(state.phase==="running"){clearInterval(timerId);state.phase="paused";render()}}
function resetTimer(){clearInterval(timerId);state.phase="idle";state.remaining=state.duration;render();note("Cronometro ripristinato")}
function countdown(){audio();unlockVoice();clearInterval(timerId);state.phase="countdown";let left=Math.max(3,+$("countdownInput").value||30);state.countdown=left;$("countdownValue").textContent=left;$("countdownSlot").textContent=state.slot.toUpperCase();$("countdownOverlay").classList.add("show");render();timerId=setInterval(()=>{left--;if(left<=5&&left>0)sound("tick");$("countdownValue").textContent=left;if(left<=0){clearInterval(timerId);$("countdownOverlay").classList.remove("show");state.remaining=state.duration;start()}},1000)}
function next(){clearInterval(timerId);state.round++;state.duration=Math.max(60,+$("minutesInput").value*60||600);state.remaining=state.duration;state.phase="idle";render();note(`Round ${state.round} pronto`)}
function eliminate(){const a=state.players.filter(p=>p.active);if(a.length<=3){note("Sono rimasti i tre finalisti");checkFinal();return}const min=Math.min(...a.map(p=>p.credit)),last=a.filter(p=>p.credit===min);if(last.length>1){speak("Attenzione. Parità sull'ultimo posto. È necessario uno spareggio.",true);note("Parità sull’ultimo posto: serve uno spareggio");return}last[0].active=false;sound("eliminate");speak(`${last[0].name} è stato eliminato.`,true);render();note(`${last[0].name} eliminato`);checkFinal()}
function checkFinal(){if(state.players.filter(p=>p.active).length===3)note("Sono rimasti i tre finalisti")}
function addPlayer(){if(state.players.length>=16){note("Limite massimo: 16 partecipanti");return}const name=$("newPlayerName").value.trim();if(!name){note("Inserisci il nome del partecipante");$("newPlayerName").focus();return}const id=Math.max(0,...state.players.map(p=>p.id))+1,station=state.players.length+1,credit=Math.max(0,+$("newPlayerCredit").value||0);state.players.push({id,name,credit,active:true,station});$("newPlayerName").value="";$("newPlayerCredit").value="100";sound("add");render();note(`${name} aggiunto alla postazione ${station}`)}
function removePlayer(){if(state.players.length<=3){note("Devono rimanere almeno 3 partecipanti");return}const removed=state.players.pop();render();note(`${removed.name} rimosso`)}
function note(m){clearTimeout(toastId);$("toast").textContent=m;$("toast").classList.add("show");toastId=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function admin(open){$("adminPanel").classList.toggle("open",open);$("scrim").classList.toggle("open",open)}
$("startBtn").onclick=start;$("pauseBtn").onclick=pause;$("resetTimerBtn").onclick=resetTimer;$("countdownBtn").onclick=()=>{admin(false);countdown()};$("nextRoundBtn").onclick=next;$("adminBtn").onclick=()=>admin(true);$("closeAdminBtn").onclick=()=>admin(false);$("scrim").onclick=()=>admin(false);
$("saveSlotBtn").onclick=()=>{state.slot=$("slotInput").value.trim()||"Da selezionare";state.chooser=$("chooserInput").value.trim()||"—";state.bet=Math.max(.1,+$("betInput").value||.5);render();note("Slot aggiornata")};$("eliminateLastBtn").onclick=eliminate;$("sortBtn").onclick=()=>{render();note("Classifica ordinata")};
$("roundInput").onchange=e=>{state.round=Math.max(1,+e.target.value||1);render()};$("minutesInput").onchange=e=>{state.duration=Math.max(60,+e.target.value*60||600);state.remaining=state.duration;render()};
$("fullscreenBtn").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>note("Schermo intero non disponibile"));
$("addPlayerBtn").onclick=addPlayer;$("removePlayerBtn").onclick=removePlayer;
$("soundBtn").onclick=()=>{state.sound=!state.sound;if(state.sound){audio();sound("add")}render();note(state.sound?"Suoni attivati":"Suoni disattivati")};
$("voiceBtn").onclick=()=>{state.voice=!state.voice;if(!state.voice){if("speechSynthesis" in window)speechSynthesis.cancel();if(currentVoiceClip)currentVoiceClip.pause()}render();if(state.voice)voiceClip("welcome");note(state.voice?"Voce attivata":"Voce disattivata")};
$("testVoiceBtn").onclick=()=>voiceClip("welcome");
$("newPlayerName").onkeydown=e=>{if(e.key==="Enter")addPlayer()};
$("resetAllBtn").onclick=()=>{if(confirm("Ripristinare tutti i dati del torneo?")){clearInterval(timerId);state=fresh();render();note("Torneo ripristinato")}};
document.addEventListener("keydown",e=>{if(e.key==="Escape")admin(false);if((e.ctrlKey||e.metaKey)&&e.key===","){e.preventDefault();admin(true)}});
setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString("it-IT",{hour12:false}),1000);render();
